// FitFit food database. Calories are estimates per listed portion.
// Home cooking varies a lot (especially oil, butter/niter kibbeh), so treat these as ballpark numbers.
window.FOODS = [
  // ---- Injera & breads ----
  { n: "Injera (1 full)", c: "Breads", e: "🫓", u: "1 large injera", k: 300 },
  { n: "Injera (half)", c: "Breads", e: "🫓", u: "1/2 injera", k: 150 },
  { n: "Injera roll", c: "Breads", e: "🫓", u: "1 rolled piece", k: 75 },
  { n: "Dabo (bread)", c: "Breads", e: "🍞", u: "1 roll / thick slice", k: 150 },
  { n: "Ambasha", c: "Breads", e: "🍞", u: "1 slice", k: 200 },
  { n: "Himbasha", c: "Breads", e: "🍞", u: "1 slice", k: 220 },
  { n: "Kita", c: "Breads", e: "🫓", u: "1 flatbread", k: 250 },
  { n: "Kocho", c: "Breads", e: "🫓", u: "1 portion", k: 250 },
  { n: "Rice", c: "Breads", e: "🍚", u: "1 cup cooked", k: 205 },
  { n: "Pasta (Ethiopian style)", c: "Breads", e: "🍝", u: "1 plate with sauce", k: 550 },
  { n: "Pasta be atkilt", c: "Breads", e: "🍝", u: "1 plate", k: 500 },

  // ---- Breakfast ----
  { n: "Firfir (injera firfir)", c: "Breakfast", e: "🍳", u: "1 plate", k: 450 },
  { n: "Chechebsa (kita firfir)", c: "Breakfast", e: "🍳", u: "1 plate", k: 600 },
  { n: "Ful", c: "Breakfast", e: "🫘", u: "1 plate (no bread)", k: 350 },
  { n: "Ful with bread", c: "Breakfast", e: "🫘", u: "1 plate + 1 bread", k: 500 },
  { n: "Ful special (egg, ayib)", c: "Breakfast", e: "🫘", u: "1 plate + bread", k: 650 },
  { n: "Enkulal firfir", c: "Breakfast", e: "🍳", u: "2 eggs", k: 250 },
  { n: "Boiled egg", c: "Breakfast", e: "🥚", u: "1 egg", k: 75 },
  { n: "Genfo", c: "Breakfast", e: "🥣", u: "1 bowl", k: 550 },
  { n: "Kinche", c: "Breakfast", e: "🥣", u: "1 bowl", k: 350 },
  { n: "Fetira (egg + honey)", c: "Breakfast", e: "🥞", u: "1 plate", k: 650 },
  { n: "Quanta firfir", c: "Breakfast", e: "🍳", u: "1 plate", k: 500 },

  // ---- Combos & fitfit ----
  { n: "Beyaynetu (with injera)", c: "Combos", e: "🍛", u: "1 platter on 1 injera", k: 750 },
  { n: "Beyaynetu (toppings only)", c: "Combos", e: "🍛", u: "all toppings, no injera", k: 450 },
  { n: "Siga beyaynetu (meat combo)", c: "Combos", e: "🍛", u: "1 platter on injera", k: 950 },
  { n: "Suf fitfit", c: "Combos", e: "🥣", u: "1 bowl", k: 450 },
  { n: "Fitfit (plain)", c: "Combos", e: "🥣", u: "1 plate", k: 400 },
  { n: "Kategna", c: "Combos", e: "🫓", u: "1 portion", k: 350 },
  { n: "Timatim fitfit", c: "Combos", e: "🍅", u: "1 bowl", k: 250 },
  { n: "Shiro fitfit", c: "Combos", e: "🥣", u: "1 plate", k: 450 },

  // ---- Wats & stews ----
  { n: "Shiro wat", c: "Wats", e: "🍲", u: "1 serving (~1 cup)", k: 250 },
  { n: "Shiro tegabino", c: "Wats", e: "🍲", u: "1 pot serving", k: 330 },
  { n: "Bozena shiro", c: "Wats", e: "🍲", u: "1 serving", k: 350 },
  { n: "Misir wat", c: "Wats", e: "🍲", u: "1 serving", k: 230 },
  { n: "Kik alicha", c: "Wats", e: "🍲", u: "1 serving", k: 200 },
  { n: "Atkilt wat", c: "Wats", e: "🥕", u: "1 serving", k: 150 },
  { n: "Gomen", c: "Wats", e: "🥬", u: "1 serving", k: 120 },
  { n: "Fosolia", c: "Wats", e: "🫛", u: "1 serving", k: 140 },
  { n: "Duba wat", c: "Wats", e: "🎃", u: "1 serving", k: 120 },
  { n: "Doro wat", c: "Wats", e: "🍗", u: "1 piece + egg + sauce", k: 450 },
  { n: "Key wat (beef)", c: "Wats", e: "🍲", u: "1 serving", k: 400 },
  { n: "Alicha wat (beef)", c: "Wats", e: "🍲", u: "1 serving", k: 350 },
  { n: "Minchet abish", c: "Wats", e: "🍲", u: "1 serving", k: 380 },
  { n: "Asa wat / goulash", c: "Wats", e: "🐟", u: "1 serving", k: 350 },

  // ---- Meat ----
  { n: "Tibs (beef)", c: "Meat", e: "🥩", u: "1 plate", k: 450 },
  { n: "Tibs (lamb)", c: "Meat", e: "🥩", u: "1 plate", k: 500 },
  { n: "Awaze tibs", c: "Meat", e: "🥩", u: "1 plate", k: 450 },
  { n: "Zilzil tibs", c: "Meat", e: "🥩", u: "1 plate", k: 450 },
  { n: "Shekla tibs", c: "Meat", e: "🔥", u: "1 clay pot", k: 600 },
  { n: "Derek tibs", c: "Meat", e: "🥩", u: "1 plate", k: 500 },
  { n: "Kitfo", c: "Meat", e: "🥩", u: "1 serving", k: 600 },
  { n: "Kitfo leb leb", c: "Meat", e: "🥩", u: "1 serving", k: 600 },
  { n: "Gored gored", c: "Meat", e: "🥩", u: "1 serving", k: 450 },
  { n: "Dulet", c: "Meat", e: "🥩", u: "1 serving", k: 350 },
  { n: "Grilled chicken breast", c: "Meat", e: "🍗", u: "1 breast", k: 280 },
  { n: "Fried fish (asa)", c: "Meat", e: "🐟", u: "1 fish", k: 400 },

  // ---- Sides & dairy ----
  { n: "Ayib", c: "Sides", e: "🧀", u: "1/2 cup", k: 100 },
  { n: "Ayib be gomen", c: "Sides", e: "🧀", u: "1 serving", k: 180 },
  { n: "Ergo (yogurt)", c: "Sides", e: "🥛", u: "1 cup", k: 150 },
  { n: "Azifa", c: "Sides", e: "🫘", u: "1 serving", k: 180 },
  { n: "Salata (salad)", c: "Sides", e: "🥗", u: "1 bowl", k: 80 },
  { n: "Senafich", c: "Sides", e: "🌶️", u: "1 spoon", k: 30 },

  // ---- Snacks & fruit ----
  { n: "Sambusa (lentil)", c: "Snacks", e: "🥟", u: "1 piece", k: 150 },
  { n: "Sambusa (meat)", c: "Snacks", e: "🥟", u: "1 piece", k: 200 },
  { n: "Kolo", c: "Snacks", e: "🌰", u: "1 handful", k: 180 },
  { n: "Dabo kolo", c: "Snacks", e: "🌰", u: "1 handful", k: 200 },
  { n: "Bombolino", c: "Snacks", e: "🍩", u: "1 piece", k: 250 },
  { n: "Roasted peanuts", c: "Snacks", e: "🥜", u: "1 handful", k: 170 },
  { n: "Popcorn", c: "Snacks", e: "🍿", u: "1 bowl", k: 150 },
  { n: "Banana", c: "Snacks", e: "🍌", u: "1 medium", k: 105 },
  { n: "Mango", c: "Snacks", e: "🥭", u: "1 mango", k: 200 },
  { n: "Orange", c: "Snacks", e: "🍊", u: "1 orange", k: 60 },
  { n: "Papaya", c: "Snacks", e: "🍈", u: "1 cup", k: 60 },
  { n: "Avocado", c: "Snacks", e: "🥑", u: "1/2 avocado", k: 120 },

  // ---- Drinks ----
  { n: "Buna (no sugar)", c: "Drinks", e: "☕", u: "1 cup", k: 5 },
  { n: "Buna (2 sugars)", c: "Drinks", e: "☕", u: "1 cup", k: 40 },
  { n: "Macchiato (no sugar)", c: "Drinks", e: "☕", u: "1 glass", k: 60 },
  { n: "Macchiato (with sugar)", c: "Drinks", e: "☕", u: "1 glass", k: 100 },
  { n: "Shai (2 sugars)", c: "Drinks", e: "🍵", u: "1 cup", k: 35 },
  { n: "Shai with milk", c: "Drinks", e: "🍵", u: "1 cup", k: 80 },
  { n: "Avocado juice", c: "Drinks", e: "🥤", u: "1 glass", k: 300 },
  { n: "Spris (layered juice)", c: "Drinks", e: "🥤", u: "1 glass", k: 350 },
  { n: "Mango juice", c: "Drinks", e: "🥤", u: "1 glass", k: 200 },
  { n: "Soda (Coke/Pepsi/Mirinda)", c: "Drinks", e: "🥤", u: "1 bottle (~300ml)", k: 130 },
  { n: "Ambo / sparkling water", c: "Drinks", e: "💧", u: "1 bottle", k: 0 },
  { n: "Beer (St. George, Habesha, Walia…)", c: "Drinks", e: "🍺", u: "1 bottle (330ml)", k: 150 },
  { n: "Tej", c: "Drinks", e: "🍯", u: "1 berele", k: 200 },
  { n: "Tella", c: "Drinks", e: "🍺", u: "1 glass", k: 120 },
  { n: "Areke", c: "Drinks", e: "🥃", u: "1 shot", k: 100 },
  { n: "Whisky", c: "Drinks", e: "🥃", u: "1 shot", k: 100 },
  { n: "Wine", c: "Drinks", e: "🍷", u: "1 glass", k: 125 },

  // ---- Junk & fast food ----
  { n: "Burger", c: "Junk", e: "🍔", u: "1 regular", k: 550 },
  { n: "Double cheeseburger", c: "Junk", e: "🍔", u: "1 burger", k: 800 },
  { n: "Pizza (slice)", c: "Junk", e: "🍕", u: "1 slice", k: 285 },
  { n: "Pizza (whole medium)", c: "Junk", e: "🍕", u: "whole pizza", k: 1800 },
  { n: "Fries / chips", c: "Junk", e: "🍟", u: "1 regular portion", k: 365 },
  { n: "Chicken shawarma", c: "Junk", e: "🌯", u: "1 wrap", k: 600 },
  { n: "Club sandwich", c: "Junk", e: "🥪", u: "1 sandwich + no fries", k: 600 },
  { n: "Fried chicken", c: "Junk", e: "🍗", u: "2 pieces", k: 500 },
  { n: "Hot dog", c: "Junk", e: "🌭", u: "1", k: 300 },
  { n: "Crisps (small bag)", c: "Junk", e: "🥔", u: "1 bag", k: 160 },
  { n: "Chocolate bar", c: "Junk", e: "🍫", u: "1 bar", k: 230 },
  { n: "Ice cream", c: "Junk", e: "🍨", u: "1 scoop", k: 140 },
  { n: "Donut", c: "Junk", e: "🍩", u: "1", k: 270 },
  { n: "Cake", c: "Junk", e: "🍰", u: "1 slice", k: 350 },
  { n: "Biscuits", c: "Junk", e: "🍪", u: "3 biscuits", k: 150 },
  { n: "Pasta carbonara", c: "Junk", e: "🍝", u: "1 plate", k: 700 },
  { n: "Lasagna", c: "Junk", e: "🍝", u: "1 portion", k: 600 },
];
window.FOOD_CATS = ["Breads", "Breakfast", "Combos", "Wats", "Meat", "Sides", "Snacks", "Drinks", "Junk"];
